development:
  community_name: Configuration Defaults Loaded - Check config/skeinlink.yml
  exception_notifier_email: 'skeinlink@example.com'
production:
  community_name: Configuration Defaults Loaded - Check configuration
  exception_notifier_email: 'skeinlink@example.com'
