name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up environment
      run: echo "RAILS_ENV=test" >> $GITHUB_ENV
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: DB setup
      run: |
        mysql -uroot -proot -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS skeinlink_test;'
        cp config/database.yml.ci config/database.yml
        bin/rails db:setup
    - name: RSpec
      run: |
        bundle exec rspec
