name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install sqlite
      run: |
        sudo apt-get install libsqlite3-dev  
    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: DB setup
      run: |
        bin/rails db:setup
    - name: RSpec
      run: |
        bundle exec rspec
